### ISSUE TITLE
Rocketchat notification

### ISSUE THREAD

**Issue by kjetilmjos** [linkedin/oncall#105]
Hi I would really like if rocketchat was a supported notification channel.

**Comment by p6knewman** [comment]
+1. We use Rocket.Chat and would really love a plugin!

**Comment by dwang159** [comment]
Merged #110, feel free to report bugs if they pop up (we're not using Rocketchat, so we probably won't run into any). Once Rocketchat implements action buttons, we can integrate this with Iris and look into deprecating this messenger.
