### ISSUE TITLE
Unclear how to use Advanced Schedules

### ISSUE THREAD

**Issue by DLu** [linkedin/oncall#112]
I'm unclear how to create advanced schedules. For sake of easy input, let's say I have two shifts that I want to rotate among my roster, All day Sunday and All day Tuesday. No matter what I do, I end up with the same schedule. 
 * 1st Sunday - User A
 * 1st Tuesday - User A
 * 2nd Sunday - User B
 * 2nd Tuesday - User B
 * etc.

My first approach was to create a schedule with multiple rows. 

My second approach was to create multiple schedules, one with the  Sunday shift, One with the Tuesday shift, and populate them one after another.

**Comment by wleese** [comment]
The scheduler seems to always use weekly rotation when creating advanced schedules.
When creating (multiple) schedules, you have no control over the order in which a person in the roster gets selected, so that too would not help.
What you're looking for I believe, would be the ability to change an advanced schedule, to rotate daily.

**Comment by houqp** [comment]
@DLu if I understand  correctly, you have one roster and would like to schedule 2 roles (1st, 2nd) on Sunday and Tuesday?

@wleese is correct that default scheduling behavior is heavily centered around weekly schedules. @dwang159 created https://github.com/linkedin/oncall/blob/master/src/oncall/scheduler/round-robin.py to enforce the order, but not sure if that would help your case without knowing what exactly your use-case is.

**Comment by DLu** [comment]
Given my example above, I'd like
  * 1st Sunday - User A
 * 1st Tuesday - User B
 * 2nd Sunday - User A
 * 2nd Tuesday - User B

I was looking for something that rotated daily, or even subdaily like 3 shifts a day, but honestly, I've given up trying to use this project.
