### ISSUE TITLE
 libldap2-dev

### ISSUE THREAD

**Issue by jegkiralyfi** [linkedin/oncall#130]
Dear Maintainer,

I'm maybe stupid but I'm not able to install the app. Any of Linux distro I get the same error massage:

The following packages have unmet dependencies:
 libldap2-dev : Depends: libldap-2.4-2 (= 2.4.40+dfsg-1+deb8u3) but 2.4.44+dfsg-5+deb9u1~bpo8+1 is to be installed
E: Unable to correct problems, you have held broken packages.

Please help me overcome!

Many thanks!
Zoltan

**Comment by dwang159** [comment]
Seems to imply you have a hold on libldap. Try following https://askubuntu.com/questions/164587/how-can-you-unhold-remove-a-hold-on-a-package (`sudo apt-get unhold libldap`) and try installing again.

**Comment by jegkiralyfi** [comment]
Many thanks! Unfortunately doesn't work. Can you please advise me a working environment? I mean what kind of Linux and webserver arhitecture is proven in working environment?

**Comment by dwang159** [comment]
I think our CI is based on Ubuntu 14.04. In production/development at Linkedin, we're using RHEL6/7, along with Mac OSX Sierra (10.12).

**Comment by jegkiralyfi** [comment]
With Docker it works.
