### ISSUE TITLE
user has god = 1, but cannot admin all teams

### ISSUE THREAD

**Issue by wleese** [linkedin/oncall#135]
This surprised me.
It seems that changing the /team/admins api to always return all god users would solve this, but not sure if this would be desirable.

How to proceed?

**Comment by shoxv** [comment]
@dwang159 Can comment more on the API change, but for the frontend we just use a bookmarklet so expose all the admin functionality. ( Of course the api wont accept the changes unless you have god mode privileges ).

You can create a new bookmark with this snippet as the URL to have the frontend treat you as an admin:

`javascript:(function()%7Boncall.team.info.checkIfAdmin %3D function()%7B oncall.team.info.data.teamData.isAdmin %3D true%3B%7D%3B oncall.team.calendar.checkIfAdmin %3D function()%7B oncall.team.calendar.data.teamData.isAdmin %3D true%3B  %7D%3B %24(%27.content-wrapper%27).attr(%27data-admin%27, true)%3B %7D)()%3B`

**Comment by wleese** [comment]
@shoxv interesting approach!

I'm fine either way (bookmarklet vs this PR), although I prefer software that doesn't have surprises. Having multiple places (edit DB - there is no UI - and add bookmarklet to browser) to enable admins to actually be admins seems less intuitive. 

If the bookmarklet approach is preferred, let's get it in the readme and docs somewhere.

**Comment by dwang159** [comment]
I do think building it into the UI is better practice; the bookmarklet that we have is mostly a lazy way out for us. I'll comment on #136 and merge after it's addressed. 

Also, I think the version of the bookmarklet that @shoxv posted is an old version, the one posted below should also refresh the calendar to allow god users to edit calendars for teams they are not a part of.

`javascript:(function(){oncall.team.info.checkIfAdmin = function(){oncall.team.info.data.teamData.isAdmin = true; }; oncall.team.calendar.checkIfAdmin = function(){ oncall.team.calendar.data.teamData.isAdmin = true; }; $('.content-wrapper').attr('data-admin', true); $('#calendar-container').incalendar('updateCalendarOption', 'readOnly', false, true); })();`
