### ISSUE TITLE
Support for locales / translations

### ISSUE THREAD

**Issue by bjoern812** [linkedin/oncall#145]
Hi,
are there any plans to translate in other languages and/or use locales?

Especially, the support for locales are very interesting, because the display of the calendar
and the dates are different i.e. in Germany where weeks starts at Monday, instead of Sunday
and the date is in format of Day.Month.Year instead of Month/Day/Year.

The date format can confuse users in Germany, because 2/11/2018 (February, 11 2018) can be
interpret to 2nd of November 2018 very fast.

Thanks for attentions.
Bjoern (from Germany)

**Comment by dwang159** [comment]
@bjoern812 Unfortunately we don't have very many resources on the internationalization side of things, so I think it's unlikely that we'll get multiple language support in the near future. On the other hand, it might be possible to toggle which weekday the calendar begins on. Maybe @shoxv could comment on how feasible that would be?

**Comment by shoxv** [comment]
@bjoern812 As Daniel mentioned, we don't have very many resources when it comes to internationalization. For the date format issue, I think we might be able to address this issue in our roadmap as one of the goals we've had is making the date format customizable in the config, so you would be able to pass in DD/MM/YYYY.

As for starting the calendar on Monday, there's no plans of adding support for something like that, sorry.

**Comment by bjoern812** [comment]
Hi @dwang159 @shoxv 
thanks for your responses. I almost thought so.
Making date format customizable in the config sounds great.
Looking forward for this.

Greetings
Bjoern
