### ISSUE TITLE
Attempt to delete/recreate a team fails:  team exists

### ISSUE THREAD

**Issue by ramjr** [linkedin/oncall#148]
This is my first go with oncall.  The system was installed by another person, so I'm working with an existing environment.

I created a team named 'tools', played around a bit and decided to recreate it, based on what I had learned.  So I used the option to "Delete team", found in the "Team Info" page.

All references to the team in the web UI disappeared, as expected.

Attempting to create a "new" team using the name "tools" fails, with the error 'Failed: team name "Tools" already exists'.

This is not what I would expect.  And is there a way to do the above that I missed, or is this a bug?

**Comment by dwang159** [comment]
@ramjr Yes, this is a limitation with our soft deletion; teams are marked inactive in the database rather than deleted to preserve their old calendars. We can probably look into appending some "_deleted" suffix on deletion; which would probably fix the issue (but be a bit of a hack). Still probably better than what we have today.

**Comment by ramjr** [comment]
Thanks for the quick response.  That makes good sense, when you think about it, with respect to the “soft” deletion.

I would suggest having both a “soft” and a “hard” deletion, allowing what you have currently and the abilitiy to remove completely the team, and all associated items.  This hard deletion could be limited by a global flag, so it is only available in the “dummy” environment, so users can experiment and then cleanup completely, to try again.

Just a thought 😉

**Comment by diegocepedaw** [comment]
this issue was fixed in #188
