### ISSUE TITLE
Gui checkbox & global flag not working

### ISSUE THREAD

**Issue by UserHIJ** [linkedin/oncall#160]
Sooo, I won't lie and say I'm a JS expert, but I have a pretty good understanding of what's going on in oncall.js. But for the life of me, I can't get a checkbox I've added to Browse Teams to work. I need the renderTeams function to be able to interrogate the value of a gui checkbox. So I tried adding a checkbox to index.html. I tacked on a change event and it wouldn't fire unless I put it in a window.onload event. But it worked. Then I tried setting a global flag based on the checkbox and I can't get the renderdata function to read it properly.  Sooo I need some help here. What is the recommended way to add a checkbox element onto the browse teams page : and how do I get it's change event to be read.

**Comment by dwang159** [comment]
Can you fork the repo, commit your changes, and link it here? I don't think we're doing anything too out of the ordinary in Javascript land, so standard practices should work just fine.

**Comment by UserHIJ** [comment]
I can't really - work doesn't allow it. But simply put . .. I'd love to know how to add a checkbox safely to the oncall application, specifically in the browse teams page. I'd like to rerun the browseteam method and interrogate the value of that checkbox. And this seems to elude me .. I'd love to know what a basic framework of getting this accomplished looks like.

**Comment by dwang159** [comment]
I'm not sure if I understand what you want, but see the commit linked below: https://github.com/dwang159/oncall/commit/ecc9defd9c82debb8d47e76fc10bb09e118c47ed

This adds a checkbox to the Browse Teams page, with some console logs attached to browse.renderPage and a checkbox on change event.

**Comment by UserHIJ** [comment]
Hi there .. 
Thanks so much .. you've really captured a lot of what I want to do . Without any really gui elements in oncall there's no real example of adding this kind of element. So look I hate asking, but what would you recommend for refreshing that table .. I can figure out how to change the results based on the toggle switch, but refreshing the page (I've tried location.reload and (#div).load ... which should reload a div once) 
Any .. advice? And for real I very much appreciate any thoughts.

**Comment by dwang159** [comment]
I'd move the call to `browse.events()` into `init()` in the `renderPage()` function, then just call `getData()`. That should refresh the content. If you're trying to add more teams in there based on a checkbox, you can probably modify the `renderPage()` function to add additional teams into `dataArr` based on the checkbox state. Just remember to move the `events()` call, otherwise you'll have duplicate event handlers.

**Comment by UserHIJ** [comment]
Okay so I tried moving the event to both init and renderpage and neither work because the click event's 'this' object is the switch, not the oncall application. Sooo I'm trying to puzzle out how I can get around that.

**Comment by UserHIJ** [comment]
when browse init is called it's called using self.browse.init. Which passes the self object to the method. When using the event handler I don't have access to that self object .. so any call to render or init or anything fails with .. template not found or the like. Cause there's no 'this' object.

**Comment by dwang159** [comment]
Outside of that function, you can define `var self = this` to get access to oncall.browse through `self`. Alternately, you can do a `oncall.browse.init()` if you're worried about what `this` is. `this` is kind of complicated in Javascript; you can do some reading on it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) if you're interested, but the `self = this` things works pretty well to make the parent object available to event handlers.

**Comment by UserHIJ** [comment]
Dwang -- i went with arrow functions and figured 'this' out. 
And for sure I'm in init ... thank you so much for your guidance.
