### ISSUE TITLE
security -- /teams/all page

### ISSUE THREAD

**Issue by UserHIJ** [linkedin/oncall#165]
Am I wrong or does the out of the box oncall application allow you to skirt security by going to http://site.com/teams/all .. without a successful login?

**Comment by jensenja** [comment]
I don't think this is a security issue - if you want to check out who is oncall for a given team, then you should be able to do so without needing an account. The login enforcement does occur if you aren't logged in and try to modify rosters/members/calendar events etc. for a given team.

**Comment by jensenja** [comment]
Maybe the maintainers could implement a public/private boolean to determine if a team and its calendar/events/members etc should be viewable by anyone or only logged in users.

**Comment by dwang159** [comment]
Closing since #181 addresses this.
