### ISSUE TITLE
Issues with testing with containers

### ISSUE THREAD

**Issue by JenkiesSpark** [linkedin/oncall#178]
Hi - I'm having issues testing this tool with the Container instructions:
https://oncall.tools/docs/admin_guide.html

I get 404 or internal error...three different people have the same issue.  I'm not sure where best to log this issue.

**Comment by JenkiesSpark** [comment]
After some more testing and help from others, we discovered it's the enhanced security required for MySQL 8.  If you give the command a mysql tag of 5.5 (mysql:5.5) it resolves the issue.

**Comment by dwang159** [comment]
:+1: I think that MySQL changed their default authentication plugin in version 8, from mysql_native_password to caching_sha2_password (see https://dev.mysql.com/doc/refman/8.0/en/sha256-pluggable-authentication.html). This might require a few configuration changes or a version bump in PyMySQL to get running. Alternately, changing the MySQL auth plugin might also do the trick.

**Comment by jordo1138** [comment]
See  PR206, true that you can change the default auth plugin, but since the point is to test quickly, my PR suggestions sing mysql:5.7 docker in the docker run two lines to get up and running
