### ISSUE TITLE
Add Note to Install OpenLDAP

### ISSUE THREAD

**Issue by manufacturedba** [linkedin/oncall#2]
Received the following error when running `python setup.py develop`
```
    In file included from Modules/LDAPObject.c:9:0:
    Modules/errors.h:8:18: fatal error: lber.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Should save a few minutes by specifying it's a prerequisite.  Maybe provide platform specific instruction?  `apt-get install libldap2-dev` ?

**Comment by houqp** [comment]
Yes! We haven't started working on the documentation yet. Literally just passed the internal review and got the code out couple hours ago ;)

You are welcome to submit PRs to help document this. We will be releasing docker images and helm pcakges later this week too.

**Comment by houqp** [comment]
FWIW, we only support syncing users from ldap right now, so you will have to manually create users in DB for now. We are working on rolling out alternative auth modules next week to help people set it up in environments without ldaps.

**Comment by manufacturedba** [comment]
Good note.  I'll send my PR anyway knowing ldap isn't the only option in the future.

**Comment by kayrus** [comment]
@houqp have you released helm charts? I haven't found them.

**Comment by houqp** [comment]
@kayrus sorry, I dropped the ball on that one :( The chart should be very straight forward to implement though, oncall itself is stateless so you just need to hook it up to mysql.

**Comment by lukdz** [comment]
@kayrus @houqp I'm working on helm chart for oncall and should be ready to make a pull request by the end of the week. If official image of oncall at https://quay.io/repository/iris/oncall could be updated that would be great.
