### ISSUE TITLE
wrong message of "user jdoe is already in the roster"

### ISSUE THREAD

**Issue by liuzhen** [linkedin/oncall#221]
0 build docker as the ops/packer

1 ```run --name mysql -e MYSQL_ROOT_PASSWORD='1234' -d mysql --default-authentication-plugin=mysql_native_password```

2 ```docker run --name oncall -d --link mysql:mysql -p 8080:8080 -e DOCKER_DB_BOOTSTRAP=1 quay.io/iris/oncall```

3
manually add new user "test" into table `user` & `user_contact` or
in the oncall docker, setup  oncall-admin then create user `test` (with extra docker param of -p 16652:16652)

note that: it seems I have to fix
https://stackoverflow.com/questions/45368336/error-keyerror-255-when-executing-pymysql-connect
https://stackoverflow.com/questions/50156520/cannot-connect-to-a-local-mysql-db-with-sqlalchemy-on-windows-machine
in order to make oncall-admin work (so is iris)

4
log as "test", create team of 'team foo", add roster of 'roster bar', then try to add user of "jdoe" to "roster bar", it complains "user jdoe is already in the roster"

I have checked out the api code, where the exception is except-ed generally, meaning that any db error would tell user "user * is already in the roster".

anything I missed?

**Comment by zenman94** [comment]
Dear liuzhen,

That happen only in an empty roster. I found : 
```
cursor.execute('''SELECT `roster`.`id`, COALESCE(MAX(`roster_user`.`roster_priority`), -1) + 1
                          FROM `roster_user`
                          JOIN `roster` ON `roster_id` = `roster`.`id`
                          JOIN `team` ON `team`.`id`=`roster`.`team_id`
                          WHERE `team`.`name`=%s AND `roster`.`name`=%s''',
                       (team, roster))
```

That return a "NULL" roster.id.

Regards

**Comment by liuzhen** [comment]
thanks, but that kind fix would be terrifying to the new adopters;
git-blame says it is a one-year old sql, i start to suspect there will be more bugs lurking

**Comment by liuzhen** [comment]
hi, comments besides closing it will be appreciated, we are anxiously waiting to be corrected.


________________________________
收件人: Diego Cepeda <notifications@github.com>
发送时间: 星期四, 十月 25, 2018 01:47
收件人: linkedin/oncall
抄送: liuzhen; Author
主题: Re: [linkedin/oncall] wrong message of "user jdoe is already in the roster" (#221)


Closed #221<https://github.com/linkedin/oncall/issues/221>.

―

**Comment by diegocepedaw** [comment]
@liuzhen, the fix that @liuzhen pointed out here was merged in with PR #222. Do you still see this problem with this fix? If so i can reopen this issue.

**Comment by dwang159** [comment]
It looks like this bug occurs in later versions of MySQL, and not in the one we use in production (5.6). @zenman94's fix looks correct.

**Comment by liuzhen** [comment]
@diegocepedaw @dwang159  Thanks to you. I will stick to MySQL 5.6
