### ISSUE TITLE
Calendar display error with Team Subscriptions

### ISSUE THREAD

**Issue by sfamilia** [linkedin/oncall#243]
Calendar display for any Team with an added Subscription appears to be broken:

All Events and Subscriptions display correctly when the Calendar is loaded but navigating to the next week or month, or changing from Week to Month, displays a blank calendar. When I navigate back, the original Calendar is blank and requires a page refresh to display schedules again. 

Being able to navigate visually and review schedules is critical to us, as is using the Subscription feature. 

This might be a related (or the same) issue referenced in [linkedin/iris#330](https://github.com/linkedin/iris/issues/330)

>  I think the calendar display for subscribed events is a little rough around the edges as well, but I haven't been able to get the time to throw that together. I think I'll check in with our web dev and our designer at LinkedIn and see what they're thinking about it.

**Comment by dwang159** [comment]
Can you provide any output that the development console is giving, and/or any exceptions from the Python backend? I haven't been able to reproduce this behavior. We recently migrated to Python 3, and I did a bad job with branches for Oncall, so checking out b688b3c88551d3f0379dd13748ea066f91d890a2 may work if your environment is still 2.7

**Comment by sfamilia** [comment]
We discovered that the issue was related to an edit we made. Thanks!
