### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ibril15** [linkedin/oncall#248]
Hello,

It looks like the Python 3 related commits have been reverted.  Was there a specific reason for that?  I have a clone of the repo with 850c4bd062d8ffb3071514fa2913b1685fe2ec52 (2/28) as the latest and I got it working with Python 3.  Is there a plan to convert the project to Python 3 again?

Thanks.

-Igor

**Comment by diegocepedaw** [comment]
Hey Igor,
We moved the Python 3 version to its own branch (py3). We are still doing active development on the py3 branch and the plan is to eventually merge it into the master branch as a major version bump.
-Diego

**Comment by ibril15** [comment]
Got it, thanks for the response!

-Igor
