### ISSUE TITLE
User sync not working

### ISSUE THREAD

**Issue by lkoerting** [linkedin/oncall#352]
While performing an user sync I'm receiving an error.

`sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1")`
`[SQL: SELECT name FROM user WHERE active = FALSE AND name IN %s]`

I have check that the LDAP connection is working properly and that data is coming in.
This issue is occuring in multiple versions that I have tested so far (1.4.1, 1.4.2, 1.4.3).

Is this a known issue and how can I fix this?

**Comment by diegocepedaw** [comment]
@lkoerting do you know the value of the variable being interpolated into that query? We are currently running 1.4.1 and haven't encountered this issue.

**Comment by lkoerting** [comment]
@diegocepedaw sorry for getting back to you. I found the issues was related to an error in the ldap search configuration on my end.
After I fixed that the sync worked fine.
