### ISSUE TITLE
API authentication

### ISSUE THREAD

**Issue by MattCrum1** [linkedin/oncall#355]
Hi all - any clues on how to enable authentication for the REST API? I've got LDAP auth working for the UI using the docker-compose file / mounted config... is there a configuration option to force authentication? 

Thanks in advance.

**Comment by diegocepedaw** [comment]
@MattCrum1 you can set the require_auth config to true. From config.yaml

```
# Setting to determine whether the Oncall API/frontend is available unauthenticated.
# Set to True to force login splash page and authentication on API calls and False to allow read
# APIs without authentication
require_auth: False
```

**Comment by MattCrum1** [comment]
Thanks @diegocepedaw - I think the issue is that the config.docker.yaml file doesn't contain any of these comments or the require_auth line; might be worth updating it to include them?
