### ISSUE TITLE
user and password to portal?

### ISSUE THREAD

**Issue by joshrain** [linkedin/oncall#70]
hello, what is the easiest way to create user/pass in the portal?

i had to load the dummy_data.sql and then login using root/root.  any other password would not work? and i did not see the password defined in the sql file.

once i login, i don't see a way to create additional users?  do i have to insert into database or is there a simpler way to add users?

**Comment by dwang159** [comment]
See https://github.com/dwang159/oncall-admin for a small webapp that can help with user creation/editing. Authentication is currently handled externally, with pluggable auth modules. By default, the debug auth module should be enabled, which accepts any password given a valid username. 

I've also opened up an issue for implementing more authentication modules within Oncall: #72 .

**Comment by nicosto** [comment]
Hi, I like oncall and  looking to plug this to AD
Can we have some info how to support LDAP auth in the documentation for non Python experts.
Many thanks

**Comment by houqp** [comment]
@dwang159 looks like we forgot to release a LDAP sync/auth module for the community?

**Comment by joedissmeyer** [comment]
@nicosto The currently provided LDAP plugin worked just fine for me to enable Active Directory authentication for my test instance (but still needed to have the username in the MySQL schema before login would work - more details below).
Look in the e2e project folder after you deploy the application somewhere and get it running....

Ex:    ./e2e/test_login.py

Line 15 is where the plugin starts. You'll need to edit lines 16 through 19 to match your own AD environment. After editing the config, restart the oncall app.

Note: Even if you add in AD authentication using the LDAP plugin the current configuration still requires that the user name exists in the login table in the MySQL schema. I haven't yet figured out how to just allow all AD users to log in, or how to allow for a standalone user authentication. I would much rather prefer to have a full standalone authentication system in OnCall.

I hope this helps.

**Comment by dwang159** [comment]
Fixed with #77
