### ISSUE TITLE
Login info

### ISSUE THREAD

**Issue by kjetilmjos** [linkedin/oncall#71]
I have installed everything and it works, but I can not find any username and password to use for login via the web page. Is there a default admin user or how should I make a new one?

**Comment by dwang159** [comment]
See https://github.com/dwang159/oncall-admin for a small webapp that can help with user creation/editing. Authentication is currently handled externally, with pluggable auth modules. By default, the debug auth module should be enabled, which accepts any password given a valid username. If you've imported the dummy data, try logging in with root:root to get a default admin user.

I've also opened up an issue for implementing more authentication modules within Oncall: #72 .

**Comment by kjetilmjos** [comment]
Looks very nice I will give it a try as soon as I get home.

**Comment by kjetilmjos** [comment]
Did some testing today. Your tool looks very good mate! I would love to see this as a part of the oncall software. A couple of issues I found was when I have created a user and logged in the name is not displayed in the settings page. Other contact details are. Was also not able to set users as admin using the oncall-admin.

**Comment by dwang159** [comment]
Good to hear that it (mostly) works! Really credit goes to @jrgp; I mostly took this from his iris-admin tool. I've made a new commit that should fix the issues you've described.

**Comment by yalvinz** [comment]
njelimet banget seh kek nama loe
