### ISSUE TITLE
KeyError: 'image_url' when trying to run oncall-user-sync

### ISSUE THREAD

**Issue by joedissmeyer** [linkedin/oncall#80]
When trying to run oncall-user-sync I ran into an issue trying to perform an LDAP sync with my local Active Directory user OU.

Note: OnCall binaries are installed to /usr/bin/oncall
Copy of error:
```
$ /usr/bin/oncall-user-sync /home/oncall/configs/config.yaml
2017-08-02 15:05:17,596 INFO oncall.metrics Loaded metrics handler dummy
2017-08-02 15:05:17,596 INFO oncall.metrics Loaded metrics handler dummy
2017-08-02 15:05:17,597 INFO root Starting user sync loop at 1501700717.6
2017-08-02 15:05:17,597 INFO root Starting user sync loop at 1501700717.6
2017-08-02 15:05:17,890 INFO root Loaded 300 entries from ldap.
2017-08-02 15:05:17,890 INFO root Loaded 300 entries from ldap.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent-1.2.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/oncall/src/oncall/user_sync/ldap_sync.py", line 300, in main
    sync(config, engine)
  File "/home/oncall/src/oncall/user_sync/ldap_sync.py", line 207, in sync
    user_id = engine.execute(user_add_sql, (username, full_name, LDAP_SETTINGS['image_url'] % username)).lastrowid
KeyError: 'image_url'
Wed Aug  2 15:05:17 2017 <Greenlet at 0x3112eb0: main({'user_sync': {'activated': True, 'module': 'oncal)> failed with KeyError
```

As a workaround I modified line 209 in ldap_sync.py from this:
```
user_id = engine.execute(user_add_sql, (username, full_name, LDAP_SETTINGS['image_url'] % username)).lastrowid
```

To this....
```
user_id = engine.execute(user_add_sql, (username, full_name)).lastrowid
```

At the very least this allowed me to perform and initial sync of my Active Directory user data for the first time. I'm not concerned yet with needing to keep in constant sync as I'm testing this tool right now so I don't yet know if keeping the sync process running 24/7 will have any other errors. I'll report other errors as seen.

*From what I can tell, it looks like the ldap_sync.py script is expecting an LDAP attribute to exist called "image_url" for each object. I recommend to remove "image_url" as a requirement as not everyone will have this for their user accounts in their own LDAP/AD environments. I can create an enhancement request for this if needed.

**Comment by houqp** [comment]
@joedissmeyer yeah, the image url is a linkedin specific thing. You are welcome to submit a PR to make it optional :)

If ldap only contains part of your employee information, you might want to adapt this ldap sync script to fetch information form other sources to populate the user table.

We run this sync script 24/7 in production for years so it should be in a pretty stable state.

**Comment by joedissmeyer** [comment]
@houqp Excellent. I will go ahead and submit a PR to make this an optional thing. Thanks!

**Comment by dwang159** [comment]
@joedissmeyer Awesome to hear. If you need anything while working on this, you can find us at iris-oncall@linkedin.com or https://gitter.im/irisoncall/Lobby, and we'll be happy to help out. Looking forward to the PR!
